services:
  db:
    image: postgres:16
    container_name: subsecure-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subsecure
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: subsecure-adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata: